### ISSUE TITLE
Error when installing with gem

### ISSUE THREAD

**Issue by kdubezerra** [trivago/logstash-codec-protobuf#4] opened 2016-09-08 12:59 UTC
I'm not sure if this is an issue, so feel free to close it in case it's not.

So, instead of getting the gem file and calling `/opt/logstash/plugin install logstash-codec-protobuf-0.1.2.gem` (which works fine, but feels a bit hacky), I tried just doing `gem install logstash-codec-protobuf`, which returned with an error:

```
root@67baf8f53edd:/# gem install logstash-codec-protobuf
ERROR:  Could not find a valid gem 'logstash-core' (< 3.0.0, >= 1.4.0) in any repository
ERROR:  Possible alternatives: logstash-cli, logstash-file, logstash-lite, logstasher, logstash-fakes
```

Just in case, I added rubygems.org as a source:

```
root@67baf8f53edd:/# gem sources --add https://rubygems.org/
source https://rubygems.org/ already present in the cache
root@67baf8f53edd:/# gem install logstash-codec-protobuf
ERROR:  Could not find a valid gem 'logstash-core' (< 3.0.0, >= 1.4.0) in any repository
ERROR:  Possible alternatives: logstash-cli, logstash-file, logstash-lite, logstasher, logstash-fakes
```

It seems that it can in fact find the `logstash-codec-protobuf` gem, but it has problems with `logstash-core`. Am I doing something wrong?

**Comment by IngaFeick** [comment] 2016-09-08 13:26
Hey there! 
Well, the logstash-core is still available on rubygems but the version number is already changed to 5.x (see https://rubygems.org/gems/logstash-core) so that probably explains why it doesnt work anymore. I have not tested the codec against version 5 yet. Which logstash version are you using?

**Comment by kdubezerra** [comment] 2016-09-08 13:42
Thanks for the quick reply!
I'm using logstash 2.4.0. I have found this logstash-core gem with version also 2.4.0 in the repository though: https://rubygems.org/downloads/logstash-core-2.4.0-java.gem.
Shouldn't this be enough?

**Comment by IngaFeick** [comment] 2016-09-08 14:16
You're right. The older versions are still there. Theoretically that should work, and it actually does for me. I just tried the following on two freshly downloaded versions:

> $ cd ~/Downloads/logstash-2.3.4/
> $ gem install logstash-codec-protobuf
> Fetching: logstash-codec-protobuf-0.1.2.gem (100%)
> Successfully installed logstash-codec-protobuf-0.1.2
> 1 gem installed
> $ cd ~/Downloads/logstash-2.4.0/
> $ gem install logstash-codec-protobuf
> Successfully installed logstash-codec-protobuf-0.1.2
> 1 gem installed

I'm quite new to the whole ruby universe myself so I have to admit that I cannot currently think how to investigate this matter further, as I cannot reproduce it locally. The good news is that this will not matter anymore soon anyway as we're in the process of migrating this plugin into the official logstash repo, from which it will be available via the normal plugin install command. Since you also have already found a workaround in the download & install approach I would suggest to close this ticket for now, if you don't mind?

**Comment by kdubezerra** [comment] 2016-09-08 15:18
Sure! It even works already with:

```
$LS_HOME/bin/logstash-plugin install --version 0.1.2 logstash-codec-protobuf
```

But for some reason the installation here takes over a minute... Okay, I guess the fact that we shouldn't even use `gem install`, but `logstash-plugin install`, which already works, we can close this issue.

Thanks again for the feedback, Inga!

**Closed** 2016-09-08 15:19 UTC

**Comment by IngaFeick** [comment] 2016-09-08 15:47
Thank you, my pleasure!
